### ISSUE TITLE
KoGPT와 ChatGPT를 혼합하여 프롬프터를 구성한다

### ISSUE THREAD

**Issue by chaeeerish** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_27_BE_2#16]
## Description 🖊️
- KoGPT와 ChatGPT를 혼합하여 프롬프터를 구성한다

## To-do 🧑‍💻
- [ ] KoGPT와 ChatGPT를 혼합하여 프롬프터를 구성한다
  - 답변의 퀄리티를 위해
- [ ] GPT 에러를 수정한다
- [ ] Request 바디를 더 자세히 수정한다
