### ISSUE TITLE
Image의 생성을 고도화한다

### ISSUE THREAD

**Issue by chaeeerish** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_27_BE_2#28]
## Description 🖊️
- Image의 생성을 고도화한다

## To-do 🧑‍💻
- [ ] 이미지에서 (대표 색깔 추출해서) 어울리는 글씨 색상 만들기 (이 이미지와 어울리는 → (카피가 부각될수있는 색상 선택)
    1. https://stickode.tistory.com/577 
    2. 모델 개발
    3. 알고리즘 개발
- [ ] 이미지 글꼴 여러 개 중에 하나 랜덤으로 출력되기
- [ ] 텍스트의 크기에 맞춰서 자동으로 위치 조절되기
